name: CI (humble)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - uses: ros-tooling/action-ros-ci@v0.4
        continue-on-error: false
        with:
          target-ros2-distro: humble
