name: CI (rolling)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
          use-ros2-testing: true
      - name: Allow pip to install packages
        run: printf "[install]\nbreak-system-packages = true\n" | sudo tee -a /etc/pip.conf
      - uses: ros-tooling/action-ros-ci@v0.4
        continue-on-error: true
        with:
          target-ros2-distro: rolling
