name: CI (rolling)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
    steps:
      - name: Allow pip to install packages
        run: printf "[install]\nbreak-system-packages = true\n" | sudo tee -a /etc/pip.conf
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: rolling
